### ISSUE TITLE
App crash after added dependency

### ISSUE THREAD

**Issue by thaworn-li** [AckeeCZ/TextInputLayout#6]
I only added your library to exist project and then crash immedieatly

Caused by: java.lang.ClassCastException: cz.ackee.ui.internal.CheckableImageButton cannot be cast to com.google.android.material.internal.CheckableImageButton

**Comment by fitzsia2** [comment]
Hi! Thanks for trying our library. Can you share your app build.gradle dependencies?

**Comment by ghost** [comment]
When I use, material textinputlayout app crashes instantly.

**Comment by RahulSDeshpande** [comment]
@thaworn-li & @abalta-mobven

Guys please don't just mention what is happening.
Also mention why is it happening.

Please attach crash logs, stack-traces.
It would help others analyze the issue.

**Comment by Bartosz-Kozajda** [comment]
It seems like the app is crashing when trying to use `com.google.android.material.textfield.TextInputLayout` instead of ` cz.ackee.ui.textfield.TextInputLayout` In my app I use both views and when the library is included it's impossible to use TextInputLayout from google material library.

```
E/AndroidRuntime:   
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1014)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1144)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at androidx.fragment.app.Fragment.onCreateView(Fragment.java:1740)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     **Caused by: java.lang.ClassCastException: cz.ackee.ui.internal.CheckableImageButton cannot be cast to com.google.android.material.internal.CheckableImageButton**
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:597)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:420)
        	... 41 more
```
@fitzsia2 do you know how to resolve this?

**Comment by Bartosz-Kozajda** [comment]
I've found the issue. PR is here: https://github.com/AckeeCZ/TextInputLayout/pull/7
